### ISSUE TITLE
Can't install app directly via F-Droid: Privileged Extension keeps stopping

### ISSUE THREAD

**Issue by directentis1** [qianbinbin/fdroid-priv-ext#1]
With the another release, I was able to use this gadget on my Android 10 phone to directly install apps from F-Droid without needing manual install app-by-app.
But will the latest release, on my Magisk Delta Canary, I always get "the Extension keeps stopping".
Maybe something wrong or I need to add some packages to "su list" on the Magisk Manager?
Hope to get some helps.

Anyway, thank you for this nice stuff!

https://github.com/qianbinbin/fdroid-priv-ext/assets/128832114/c7bdec6e-ec5a-4113-ad40-393545f970f7

**Comment by qianbinbin** [comment]
Do you mean the latest version 20231025 doesn't work but old ones do?

The builtin privileged extension should be the same as old ones, as the [extension](https://f-droid.org/en/packages/org.fdroid.fdroid.privileged.ota/) hasn't been changed since 2022-01-23.

It works fine for me with [official Magisk](https://github.com/topjohnwu/Magisk).

**Comment by directentis1** [comment]
> Do you mean the latest version 20231025 doesn't work but old ones do?
> 
> The builtin privileged extension should be the same as old ones, as the [extension](https://f-droid.org/en/packages/org.fdroid.fdroid.privileged.ota/) hasn't been changed since 2022-01-23.
> 
> It works fine for me with [official Magisk](https://github.com/topjohnwu/Magisk).

I remember in the last month, I still can use it on Magisk official.
I just reinstalled my phone after reflashed with [0fe46c5a-delta(26301)](https://github.com/HuskyDG/magisk-files/releases/tag/0fe46c5a-delta) cause it allows you to hide root better while keep you security.

Maybe some things that I need to allows in root mode to use it correctly, I guess🤔️

**Comment by qianbinbin** [comment]
So it works on official Magisk? If so maybe there's something wrong with Magisk Delta.

I haven't tried Delta because my phone is in daily use. You can refer to their documentation to see if there are any relevant configuration options.

**Comment by directentis1** [comment]
> So it works on official Magisk? If so maybe there's something wrong with Magisk Delta.
> 
> I haven't tried Delta because my phone is in daily use. You can refer to their documentation to see if there are any relevant configuration options.

I'm just wondering, in addition to running your extension as a system app/an additional packer manager, does it need to use root privileges with su in any normal use cases? 

---
Magisk Delta by default is not much different compare to the original, other than isolating the ability to "see" and use the "su" binary with applications: by default applications cannot see su, unless you add them to the "mount" or "su-list".

I've added F-Droid and F-Droid Privileged Extension to sulist, but don't know why it's still crash.
Maybe I'll check the logcat and send it to you.

![](https://i.imgur.com/McBuRF6.png)

**Comment by qianbinbin** [comment]
I don't think it need root privilege. This simple module just installs two APKs:

```
/system/app/F-Droid/F-Droid.apk
/system/priv-app/F-DroidPrivilegedExtension/F-DroidPrivilegedExtension.apk
```

And for Android >= 8.0 an additional permission file is required:

```
/system/etc/permissions/permissions_org.fdroid.fdroid.privileged.xml
```

That's all the privileged extension needs.

**Comment by directentis1** [comment]
I got it. I had readded F-Droid Privileged Extension to the "su" list on Magisk Delta Manager, reboot, and tried to remove all data/cache from it and the main F-Droid app.
And now, I can installed new apps directly from F-Droid as normal!
![](https://i.imgur.com/McBuRF6.png)

Thank you for your enthusiastic help.. I will close this issue here!
 Hope it will help someone in need in the future.
