### ISSUE TITLE
 fdroid-priv-ext does not work with kernelsu 

### ISSUE THREAD

**Issue by MikolajQ** [qianbinbin/fdroid-priv-ext#3]
fdroid-priv-ext does not work with kernelsu, it constantly stops working. I use crdroid on oneplus 9 pro.

Some bug description here:
https://paste.crdroid.net/hqDXl4

How can I get it to work?

**Comment by qianbinbin** [comment]
Does this https://github.com/qianbinbin/fdroid-priv-ext/issues/1#issuecomment-1787028053 work?

**Comment by MikolajQ** [comment]
OK, solved. I had to add F-Droid Privileged Extension to the "su" list in KernelSU Manager. I thought if i install module it has root access automatically like with vanilla Magisk but it's not.
